# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e98ce5248ed81fae99fa9baca568139361c5f0ae2ed97707e2fa99a4dc002d897db2a3d1c4bb57d5832ff3e50ac3d6addd8d56fbfb7bae598f584f6cf4706ab6

test:
  secret_key_base: 606a7a106e10b6fb949f2f44a8a4d3703d1f243e08444bc31cb44a3c102a33100453001f0e7bf1131a09469c6aa3e6be102376c16a61f15eb286e7b5ab46c949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
